---
title: "Hotels"
author: "Christina Liang"
output: pdf_document
---
```{r packages, message = FALSE}
library(tidyverse)
library(infer)
```

```{r read-data}
hotel_bookings <- read.csv("~/R/DIIG/hotel_bookings.csv")
```

```{r total_nights}
hotel_bookings <- hotel_bookings %>%
  mutate(total_nights = stays_in_week_nights + stays_in_weekend_nights)
```

First, I visualized the distribution of visits to the hotels based on month of the year, to find that there was an increase in volume of arrivals in the warmer months.

```{r months}
hotel_bookings <- hotel_bookings %>%
  mutate(arrival_date_month = factor(arrival_date_month, 
                                     levels = c("January", "February", "March", "April", "May",
                                                "June", "July", "August", "September",
                                                "October", "November", "December")))
```


```{r month-distribution}
hotel_bookings %>%
  group_by(hotel, arrival_date_month) %>%
  ggplot(aes(x = arrival_date_month)) +
  geom_bar(fill = "darkblue") +
  facet_wrap(~ hotel, 
             nrow = 2, 
             scales = "free_y") +
  labs(title = "Distribution of Arrivals at Hotel by Month of the Year",
       subtitle = "Faceted by City vs. Resort Hotel",
       x = "Arrival Date Month",
       y = "Number of Arrivals")
```
I also changed the is_canceled variable from numeric to categorical, as 0 and 1 represent a booking being cancelled or not.
```{r is-canceled}
hotel_bookings$is_canceled <- as.factor(hotel_bookings$is_canceled)
```


```{r meanadr, warning = FALSE}
hotel_bookings %>%
  group_by(hotel, arrival_date_month) %>%
  summarise(meanadr = mean(adr)) %>%
  ggplot(aes(x = arrival_date_month, y = meanadr)) +
  geom_col(fill = "darkblue") +
  facet_wrap(~ hotel, nrow = 2, scales = "free_y") +
  labs(title = "Mean Average Daily Rate by Hotel",
       x = "Hotel Location",
       y = "Mean Average Daily Rate ($)")
```
```{r}
hotel_bookings %>%
  group_by(hotel, arrival_date_month) %>%
  summarise(meanadr = mean(adr))
```


For this data challenge, I'll mainly be focusing on Resort Hotels.
```{r resort-only}
resort_bookings <- hotel_bookings %>%
  filter(hotel == "Resort Hotel")
```

```{r model}
#logit_mod1 <- glm(is_canceled ~ lead_time + arrival_date_year + arrival_date_month +
              #     arrival_date_week_number + arrival_date_day_of_month + stays_in_weekend_nights +
               #    stays_in_week_nights,
               #   data = resort_bookings, family = "binomial", maxit = 100)
```

```{r}
#logit_mod2 <- glm(is_canceled ~ adults + children + babies + meal + country +
             #      market_segment + is_repeated_guest + previous_cancellations + previous_bookings_not_canceled +
              #     booking_changes + deposit_type,
               #   data = resort_bookings, family = "binomial", maxit = 100)
```

```{r}
#logit_mod3 <- glm(is_canceled ~ days_in_waiting_list + adr + required_car_parking_spaces +
               #    total_of_special_requests + reservation_status + reservation_status_date,
               #   data = resort_bookings, family = "binomial", maxit = 100)
```


